language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - autoconf-archive
            - ppp
    homebrew:
        packages:
            - autoconf-archive

before_script:
    - ./autogen.sh

script:
    - ./configure ${CONFIGURE_OPT}
    - make
    - make check

env:
    - CONFIGURE_OPT=""

matrix:
    fast_finish: true
