language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
    include:
        - os: osx
          env: CONFIGURE_OPT="--enable-xmpp"

addons:
    apt:
        packages:
            - autoconf-archive
            - ppp
    homebrew:
        packages:
            - autoconf-archive
            - libstrophe

before_script:
    - ./autogen.sh

script:
    - ./configure ${CONFIGURE_OPT}
    - make
    - make check

env:
    global:
        - PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
    matrix:
        - CONFIGURE_OPT="--disable-xmpp"
